/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hyberbin.dubbo.client.ui.frames;

import com.hyberbin.dubbo.client.config.AppConfig;
import com.hyberbin.dubbo.client.config.CoderQueenModule;
import com.hyberbin.dubbo.client.dao.SqliteDao;
import com.hyberbin.dubbo.client.domain.AppDO;
import com.hyberbin.dubbo.client.model.AppModel;
import com.hyberbin.dubbo.client.model.DependencyModel;
import com.hyberbin.dubbo.client.parser.ApiParser;
import com.hyberbin.dubbo.client.vo.AppModeVO;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.commons.lang.StringUtils;

/**
 * @author Administrator
 */
public class AddAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAppFrame
     */
    public AddAppFrame() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int x = (int) (toolkit.getScreenSize().getWidth() - getWidth()) / 2;
        int y = (int) (toolkit.getScreenSize().getHeight() - getHeight()) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        groupId = new javax.swing.JTextField();
        artifactId = new javax.swing.JTextField();
        version = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "group", "artifactId", "version"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("主依赖信息   groupId:artifactId:version");

        jLabel5.setText("其他赖信息");

        addButton.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icons/methodDefined@2x.png"))); // NOI18N
        addButton.setToolTipText("保存");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        delButton.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icons/methodNotDefined@2x.png"))); // NOI18N
        delButton.setToolTipText("保存");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/icons/commit.png"))); // NOI18N
        saveButton.setToolTipText("保存");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel6.setText(":");

        jLabel7.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(groupId)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(artifactId)
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(version)
                                                .addGap(5, 5, 5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(340, 340, 340)
                                                                .addComponent(addButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        27,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(delButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        27,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(saveButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        27,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel1))
                                                .addGap(4, 4, 4)))
                                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(artifactId)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(groupId)
                                        .addComponent(version))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addGap(7, 7, 7)
                                                        .addComponent(jLabel5,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))
                                        .addComponent(addButton,
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(saveButton)
                                        .addComponent(delButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        164, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        ((DefaultTableModel)jTable1.getModel()).addRow(new String[]{"","",""});
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        ((DefaultTableModel)jTable1.getModel()).removeRow(selectedRow);
    }//GEN-LAST:event_delButtonActionPerformed

    private boolean validate(DependencyModel model) {
        if (StringUtils.isNotBlank(model.getGroupId()) && StringUtils
                .isNotBlank(model.getArtifactId())) {
            StringUtils.isNotBlank(model.getVersion());
            return true;
        }
        JOptionPane.showMessageDialog(this, "groupId,artifactId,version都不允许为空",
                "必填信息", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    private void saveButtonActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ApiParser apiParser = CoderQueenModule.getInstance(ApiParser.class,"apiNormalStyleParser");
        DependencyModel main = new DependencyModel(groupId.getText(), artifactId.getText(),
                version.getText());
        if (!validate(main)) {
            return;
        }
        SqliteDao sqliteDao = CoderQueenModule.getInstance(SqliteDao.class);
        AppDO app = sqliteDao.getApp(artifactId.getText());
        if (app != null) {
            JOptionPane.showMessageDialog(this, "已经有相同的应用存在", "错误", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TableModel model = jTable1.getModel();
        DependencyModel[] exts = new DependencyModel[model.getRowCount()];
        for (int i = 0; i < model.getRowCount(); i++) {
            String group = (String) model.getValueAt(i, 0);
            String artifactId = (String) model.getValueAt(i, 0);
            String version = (String) model.getValueAt(i, 0);
            exts[i] = new DependencyModel(group, artifactId, version);
            if (!validate(exts[i])) {
                return;
            }
        }
        DependencyModel dependencyModel = new DependencyModel(main);
        AppModel appModel=new AppModel(main.getGroupId(),main.getArtifactId(),main.getVersion());
        AppConfig appConfig = new AppConfig();
        appConfig.setMainDependency(dependencyModel);
        AppModeVO appModeVO = new AppModeVO(appModel, appConfig);
        AppDO appDO = new AppDO(appModeVO);
        sqliteDao.saveApp(appDO);
        appModeVO.setId(appDO.getId());
        File workspace = new File(appModeVO.getWorkSpace());
        AppModel appModelParsed = apiParser
                .parseAppModel(workspace.getAbsolutePath(), dependencyModel, exts);
        appModeVO.setAppModel(appModelParsed);
        CoderQueenModule.getInstance(DubboUIFrame.class).addAppNode(appModeVO);
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField artifactId;
    private javax.swing.JButton delButton;
    private javax.swing.JTextField groupId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField version;
    // End of variables declaration//GEN-END:variables

}
